import { labEntries, labHref } from "./lab-catalog";

export type LearningTrack = "foundations" | "building" | "quality" | "operations" | "bonus";
type MissionRow = [string, LearningTrack, string, string, string, string, string, string, string, string];
export type Mission = { slug: string; track: LearningTrack; href: string; title: { cs: string; en: string }; action: { cs: string; en: string }; question: { cs: string; en: string }; choices: { cs: [string, string]; en: [string, string] } };

export const learningTracks: Array<{ id: LearningTrack; cs: string; en: string; slugs: string[] }> = [
  { id: "foundations", cs: "Základy LLM", en: "LLM foundations", slugs: ["tokenizer", "transformer", "context", "generation", "prompt-tokens", "embeddings"] },
  { id: "building", cs: "Stavba LLM aplikace", en: "Building an LLM app", slugs: ["structured-output", "chunking", "retrieval", "reranking", "rag", "tools", "agents", "mcp"] },
  { id: "quality", cs: "Kvalita a bezpečnost", en: "Quality and safety", slugs: ["datasets", "evaluators", "retrieval-evals", "grounding", "safety", "arena"] },
  { id: "operations", cs: "Provoz modelů", en: "Model operations", slugs: ["routing", "inference", "cache", "kv-cache", "quantization", "fine-tuning"] },
  { id: "bonus", cs: "Bonusová mise", en: "Bonus mission", slugs: ["flappy"] },
];

const rows: MissionRow[] = [
  ["tokenizer", "foundations", "Porovnej českou větu a kód a sleduj ID tokenů.", "Compare a Czech sentence with code and inspect token IDs.", "Jsou tokeny vždy celá slova?", "Are tokens always whole words?", "Ne. Mohou být i části slov nebo znaky.", "Ano. Jedno slovo má vždy jeden token.", "No. They can also be word pieces or characters.", "Yes. One word always has one token."],
  ["transformer", "foundations", "Vyber dva tokeny a sleduj masku attention.", "Select two tokens and inspect the attention mask.", "Může token při kauzálním generování číst budoucí tokeny?", "Can a token attend to future tokens during causal generation?", "Ne. Budoucí pozice jsou maskované.", "Ano. Každá pozice vidí celou větu.", "No. Future positions are masked.", "Yes. Every position sees the whole sentence."],
  ["context", "foundations", "Zmenši rozpočet kontextu a sleduj, co se vynechá.", "Reduce the context budget and see what is dropped.", "Co se stane, když vstup přesáhne kontextový rozpočet?", "What happens when input exceeds the context budget?", "Některé části je nutné zkrátit nebo vynechat.", "Model automaticky získá větší kontext.", "Some content must be shortened or removed.", "The model automatically gets a larger context."],
  ["generation", "foundations", "Porovnej temperature 0 a 1 při stejném seedu.", "Compare temperature 0 and 1 with the same seed.", "Co mění vyšší temperature?", "What does a higher temperature change?", "Rozložení výběru dalších tokenů.", "Množství znalostí uložených v modelu.", "The distribution used to sample next tokens.", "The knowledge stored in the model."],
  ["prompt-tokens", "foundations", "Změň systémovou instrukci u stejného dotazu.", "Change the system instruction for the same question.", "Je systémová instrukce součástí vstupu modelu?", "Is a system instruction part of the model input?", "Ano. Zabírá část kontextu a může změnit odpověď.", "Ne. Je to jen vzhled aplikace.", "Yes. It uses context and can change the answer.", "No. It only changes the app interface."],
  ["embeddings", "foundations", "Porovnej dvě podobně míněné věty s různými slovy.", "Compare two sentences with similar meaning but different wording.", "Co vyjadřuje vysoká podobnost embeddingů?", "What does high embedding similarity suggest?", "Texty mohou mít blízký význam v prostoru daného modelu.", "Texty musí mít přesně stejná slova.", "The texts may have similar meaning in that model's space.", "The texts must contain exactly the same words."],
  ["structured-output", "building", "Smaž povinné pole z ukázkové JSON odpovědi.", "Remove a required field from the sample JSON answer.", "Zaručuje platné JSON schéma pravdivou odpověď?", "Does a valid JSON schema guarantee a truthful answer?", "Ne. Kontroluje tvar, nikoli pravdivost.", "Ano. Platný JSON je vždy správný.", "No. It checks structure, not truth.", "Yes. Valid JSON is always correct."],
  ["chunking", "building", "Změň velikost a překryv úryvků dokumentu.", "Change document chunk size and overlap.", "Proč se úryvky překrývají?", "Why do chunks overlap?", "Aby informace na hranici úryvků neztratily souvislost.", "Aby každý úryvek byl totožný.", "To retain context around chunk boundaries.", "To make every chunk identical."],
  ["retrieval", "building", "Porovnej BM25 a hybridní hledání na stejném dotazu.", "Compare BM25 and hybrid retrieval on the same query.", "Kdy může vektorové hledání pomoci proti přesné shodě slov?", "When can vector retrieval help beyond exact word matching?", "Když dotaz používá jiná slova pro podobný význam.", "Jen když je dotaz doslova v dokumentu.", "When the query uses different words for a similar meaning.", "Only when the query appears verbatim in a document."],
  ["reranking", "building", "Změň důraz na relevanci a sleduj pořadí podkladů.", "Change the relevance weight and inspect passage order.", "Může přerovnání změnit odpověď bez změny dokumentů?", "Can reranking change an answer without changing documents?", "Ano. Jiné úryvky se mohou dostat do kontextu.", "Ne. Pořadí podkladů nikdy nehraje roli.", "Yes. Different passages may enter the context.", "No. Passage order never matters."],
  ["rag", "building", "V místním korpusu dole změň dokument a dotaz; sleduj nalezený podklad. S modelem můžeš zkusit i celý RAG průchod.", "Edit a document and query in the local corpus below; inspect retrieved evidence. With a model, try the full RAG pipeline too.", "Odkud má RAG odpověď získat konkrétní fakta?", "Where should RAG obtain facts for an answer?", "Z nalezených podkladů vložených do kontextu.", "Z názvu použitého modelu.", "From retrieved evidence added to the context.", "From the model name."],
  ["tools", "building", "Změň argument jednoho volání kalkulačky.", "Change one argument of a calculator call.", "Co vykoná samotný nástroj po volání modelu?", "What does the tool do after the model proposes a call?", "Aplikace ověří argumenty a vykoná povolenou operaci.", "Model automaticky získá přístup ke všem souborům.", "The app validates arguments and executes an allowed operation.", "The model automatically gets access to all files."],
  ["agents", "building", "Načti souborový příklad. Bez modelu sleduj průchod success v galerii; s modelem spusť agenta.", "Load the file example. Without a model, inspect the success trace in the gallery; with a model, run the agent.", "Jaký je rozdíl mezi agentem a jedním voláním nástroje?", "How does an agent differ from one tool call?", "Agent může opakovat smyčku rozhodnutí, nástroj, nový stav.", "Agent vždy znamená trénování modelu.", "An agent may repeat a decision, tool, state loop.", "An agent always means training a model."],
  ["mcp", "building", "Porovnej seznam nástrojů a čtení zdroje.", "Compare tool listing with resource reading.", "Rozhoduje MCP server za model, který nástroj použije?", "Does an MCP server decide which tool the model uses?", "Ne. Server popisuje schopnosti, klient a model rozhodují o volání.", "Ano. Server vždy sám vybere další krok.", "No. The server exposes capabilities; the client and model choose calls.", "Yes. The server always chooses the next step."],
  ["datasets", "quality", "Přidej testovací otázku a očekávanou informaci.", "Add a test question and an expected fact.", "K čemu slouží očekávaná odpověď v datasetu?", "What is a reference answer in a dataset for?", "K porovnání skutečné odpovědi s očekáváním.", "K tajnému doplnění znalostí modelu.", "To compare the model output with an expectation.", "To secretly add knowledge to the model."],
  ["evaluators", "quality", "Porovnej přesnou a částečnou shodu na delší odpovědi.", "Compare exact and partial match on a longer answer.", "Pozná přesná textová shoda parafrázi?", "Can exact text match recognize a paraphrase?", "Obvykle ne. Posuzuje normalizovaný text.", "Ano. Vždy rozumí významu věty.", "Usually not. It compares normalized text.", "Yes. It always understands sentence meaning."],
  ["retrieval-evals", "quality", "Změň K a sleduj Recall@K a Precision@K.", "Change K and inspect Recall@K and Precision@K.", "Co měří Recall@K?", "What does Recall@K measure?", "Podíl relevantních podkladů nalezených v prvních K výsledcích.", "Průměrnou délku odpovědi modelu.", "The share of relevant sources found in the top K results.", "The model answer's average length."],
  ["grounding", "quality", "Odstraň údaj z podkladu a sleduj tvrzení odpovědi.", "Remove a fact from evidence and inspect answer claims.", "Kdy je tvrzení podložené?", "When is a claim grounded?", "Když ho dostupný zdroj skutečně podporuje.", "Když zní sebejistě a plynule.", "When available evidence supports it.", "When it sounds confident and fluent."],
  ["safety", "quality", "Porovnej stejný útok se zapnutou a vypnutou obranou.", "Compare the same attack with a defense on and off.", "Má být instrukce nalezená v dokumentu stejně důvěryhodná jako systémové pravidlo?", "Should an instruction found in a document have system-level authority?", "Ne. Dokument je nedůvěryhodný obsah.", "Ano. Každý nalezený text je pokyn.", "No. A document is untrusted content.", "Yes. Every retrieved text is an instruction."],
  ["arena", "quality", "Porovnej dvě odpovědi na stejný vstup.", "Compare two answers to the same input.", "Proč mají modely dostat stejný testovací vstup?", "Why should models receive the same test input?", "Aby rozdíl odpovědí šel lépe připsat modelům.", "Aby odpověděly stejnými slovy.", "So differences are easier to attribute to models.", "So they answer with identical wording."],
  ["routing", "operations", "Změň prioritu z ceny na délku kontextu.", "Switch priority from cost to context length.", "Může jeden model vyhrát pro cenu a jiný pro kontext?", "Can one model win on price and another on context?", "Ano. Router vybírá podle zvoleného kritéria.", "Ne. Pořadí modelů je vždy stejné.", "Yes. The router follows the chosen criterion.", "No. Model ranking is always fixed."],
  ["inference", "operations", "Změň TTFT a přehraj streaming.", "Change TTFT and replay streaming.", "Co měří TTFT?", "What does TTFT measure?", "Čekání na první výstupní token.", "Celkový počet tokenů odpovědi.", "The wait until the first output token.", "The total output token count."],
  ["cache", "operations", "Spusť stejný dotaz dvakrát.", "Run the same question twice.", "Co se stane při zásahu přesné cache?", "What happens on an exact cache hit?", "Vrátí se uložený výsledek bez nového volání modelu.", "Model vždy odpoví znovu.", "The stored result returns without a new model call.", "The model always generates again."],
  ["kv-cache", "operations", "Zdvojnásob délku kontextu a sleduj paměť.", "Double context length and inspect memory.", "Jak se v ukázkovém výpočtu změní velikost KV cache při dvojnásobném kontextu?", "In the example calculation, what happens to KV cache size when context doubles?", "Přibližně se zdvojnásobí.", "Zůstane beze změny.", "It approximately doubles.", "It stays unchanged."],
  ["quantization", "operations", "Porovnej FP16 a INT4 pro stejný počet parametrů.", "Compare FP16 and INT4 for the same parameter count.", "Co obvykle snižuje kvantizace vah?", "What does weight quantization usually reduce?", "Paměť potřebnou k uložení vah.", "Počet vrstev modelu.", "Memory needed to store the weights.", "The number of model layers."],
  ["fine-tuning", "operations", "Porovnej měnící se fakta a stálý styl odpovědí.", "Compare changing facts with a stable response style.", "Co je vhodnější pro často měněná fakta?", "What better handles frequently changing facts?", "Aktuální externí podklady, například RAG.", "Znovu trénovat model po každé změně.", "Fresh external evidence, such as RAG.", "Retrain the model after every change."],
  ["flappy", "bonus", "Spusť stejnou trať se dvěma agenty a porovnej jejich rozhodnutí.", "Run the same course with two agents and compare decisions.", "Je trénování herního agenta totéž jako generování dalšího tokenu LLM?", "Is training a game agent the same as LLM next-token generation?", "Ne. Cíl, akce a zpětná vazba jsou odlišné.", "Ano. Jde o přesně stejný úkol.", "No. Goals, actions, and feedback differ.", "Yes. It is exactly the same task."],
];

const extraNames: Record<string, { cs: string; en: string; href: string }> = {
  datasets: { cs: "Datasety", en: "Datasets", href: "/datasets" },
  evaluators: { cs: "Evaluátory", en: "Evaluators", href: "/evaluators" },
  arena: { cs: "Aréna modelů", en: "Model arena", href: "/arena" },
};

export const missions: Mission[] = rows.map(([slug, track, actionCs, actionEn, questionCs, questionEn, correctCs, wrongCs, correctEn, wrongEn]) => {
  const entry = labEntries.find((item) => item.slug === slug);
  const extra = extraNames[slug];
  return { slug, track, href: extra?.href ?? labHref(slug), title: { cs: entry?.cs ?? extra?.cs ?? slug, en: entry?.en ?? extra?.en ?? slug }, action: { cs: actionCs, en: actionEn }, question: { cs: questionCs, en: questionEn }, choices: { cs: [correctCs, wrongCs], en: [correctEn, wrongEn] } };
});

export function missionBySlug(slug: string) { return missions.find((mission) => mission.slug === slug); }
export const learningProgressKey = "llmlab.learningProgress.v1";
